CREATE TABLE tb_categorias(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
tecnologia VARCHAR(50) NOT NULL,
turma VARCHAR(6) NOT NULL
);


CREATE TABLE tb_starters(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
cpf VARCHAR(11) NOT NULL,
quatro_letras VARCHAR(4) NOT NULL,
email VARCHAR(50) NOT NULL,
categoria BIGINT NOT NULL,
FOREIGN KEY (categoria) REFERENCES tb_categorias(id)
);

CREATE TABLE tb_perfis(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL
);

CREATE TABLE tb_usuarios(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
login VARCHAR(50) NOT NULL,
senha VARCHAR(100) NOT NULL,
perfil BIGINT NOT NULL,
FOREIGN KEY (perfil) REFERENCES tb_perfis(id)
)
